### ISSUE TITLE
t.sort is not a function

### ISSUE THREAD

**Issue by linonetwo** [tiddly-gittly/tw-gamification#22]
```
Uncaught TypeError: t.sort is not a function
    at checkEventCacheDebounceDuplication (handle-reality-event-cache.js:1:25468)
    at checkAndPushAnItemToLogAndCacheFile (handle-reality-event-cache.js:1:26424)
    at eval (handle-reality-event-cache.js:1:27495)
    at Array.forEach (<anonymous>)
    at Widget.eval (handle-reality-event-cache.js:1:27481)
    at eventListeners.<computed> (widget.js:638:19)
    at Widget.dispatchEvent (widget.js:652:7)
    at dispatchAddRealityEventBatch (handler.js:1:23698)
```

```js
function checkEventCacheDebounceDuplication(e, t, o) {
///。。。
return t.sort((e,t)=>t.event.timestamp - e.event.timestamp).findIndex(e=>{
```

**Comment by linonetwo** [comment]
点击itkg里的完成任务时发现

**Comment by linonetwo** [comment]
fc2f90f

**Comment by linonetwo** [comment]
<img width="1365" alt="截屏2024-05-13 19 28 46" src="https://github.com/tiddly-gittly/tw-gamification/assets/3746270/ca3c209d-de05-4417-8a93-5a47649e2b78">
<img width="1592" alt="截屏2024-05-13 19 29 28" src="https://github.com/tiddly-gittly/tw-gamification/assets/3746270/6a3bc9d3-b12c-468a-afbb-7c588f5bf7fb">

应该是用 e.sort 才对，不过这边都是对象，没有数组
